hashicorp/packer-plugin-docker

.github/workflows/generate-docs-artifacts.yml

Adding workflow for generating docs artifacts on release. This step is needed in order for remote plugin docs to get ingested into Packer.io :partying_face: 
Requires https://github.com/hashicorp/packer/pull/10656/
To actually add the files to Packer.io we need to open a PR against `website/data/docs-remote-plugins.json` in the Packer repo with a block that looks like this
```json
{
"title": "Docker",
"path": "docker",
"repo": "hashicorp/packer-plugin-docker"
}
```

Add base workflow for generating doc artifacts

---

docs/post-processors/docker-save.mdx
docs/post-processors/docker-tag.mdx
post-processor/docker-tag/post-processor.go
post-processor/docker-tag/post-processor_test.go

Hi there,
Noticed a few issues on the main repo of packer, but realized this has since been moved to a new repo, so opening up a fresh PR against this one!
This PR contains:
- docs: fix post-processor hcl examples for docker-save and docker-tag postprocessors.
- fix code comment misspelling.
- fix misspelling in assertion.
Cheers!

Post-Procesor hcl examples and misspelling fixes

---

docs/post-processors/docker-tag.mdx

Doc change: Examples were outdated and had wrong syntax

fix: update examples to match and fix syntax

---

docs/builders/docker.mdx

With the provided examples, packer threw the following error:
```
Error: Failed preparing post-processor-block "docker-import" ""
on ./config.pkr.hcl line 64:
(source code not available)
./config.pkr.hcl:66,13-23: Incorrect attribute value type; Inappropriate value
for attribute "tag": string required.
==> Wait completed after 2 microseconds
==> Builds finished but no artifacts were created.
```

Fix wrong hcl docker-import post-processor example

---

docs/builders/docker.mdx

Revert doc fixes that fixed a bit too many docs. It would probably be worth it to have everything be named `tags` here.

revert doc fixes

---

builder/docker/config.go
builder/docker/config.hcl2spec.go
builder/docker/driver.go
builder/docker/driver_docker.go
builder/docker/step_run.go
docs-partials/builder/docker/Config-not-required.mdx

In order to support other runtimes than runc, the `runtime` parameter is added to enable the `--runtime` option to the `docker run` command used to launch the container.

Add runtime configuration option

---

builder/docker/driver_docker.go
post-processor/docker-push/post-processor.go

When running multiple `docker-push` post processors concurrently, there
was a race condition where one `docker-push` post processor would finish
and call `docker logout` to  remove the credentials for a given registry
while another `docker-push` post processor was still running, causing
the other `docker-push` post processor to no longer have access to the
registry credentials to perform a `docker push`.
Since the underlying `DockerDriver` shells out to raw `docker` commands,
calls to `Login` store registry credentials in the default Docker client
configuration directory. Additionally, calls to `Logout` remove registry
credentials from the default Docker client configuration directory.
Since Packer post processors are unaware of each other, one
`docker-push` post processor was removing …

docker-push: use isolated client configuration

---

builder/docker/config.go
builder/docker/config.hcl2spec.go
builder/docker/driver.go
builder/docker/driver_docker.go
builder/docker/driver_mock.go
builder/docker/step_pull.go
builder/docker/step_run.go
docs-partials/builder/docker/Config-not-required.mdx
docs/builders/docker.mdx
docs/post-processors/docker-import.mdx
docs/post-processors/docker-push.mdx
post-processor/docker-import/post-processor.go
post-processor/docker-import/post-processor.hcl2spec.go
post-processor/docker-push/post-processor.go
post-processor/docker-push/post-processor.hcl2spec.go

Adding support for `--platform` arg on pull, push, import and run.
Closes #97

Support `--platform` docker CLI argument to target the platform specific image architecture

---

builder/docker/ecr_login.go
post-processor/docker-push/post-processor_test.go

- This PR adds the ability to push docker images to [ECR Public](https://docs.aws.amazon.com/AmazonECR/latest/public/what-is-ecr.html)
- From the user's perspective, nothing has been changed. All they need to do is to use the ECR Public URI as the `login_server`.
- Make sure to have right `aws` credentials set
```hcl
source "docker" "ubuntu-bionic" {
image  = "ubuntu:bionic"
commit = true
}
build {
name = "docker-push-ecr-public"
sources = [
"source.docker.ubuntu-bionic"
]
post-processors {
post-processor "docker-tag" {
repository = "public.ecr.aws/j9y7g6y8/dev_hc_pkr_dkr_test_1"
tags       = ["packer-rocks", "burrito-boi"]
}
post-processor "docker-push" {
ecr_login    = true
aws_profile  = "default"
login_server = "https://public.ecr.aws/j9y7g6y8/dev_hc_pkr_dkr_test_1"
}
}
}
``` …

Add ability to push/pull docker images to/from Amazon ECR Public Gallery

---

builder/docker/config.hcl2spec.go
builder/docker/ecr_login.go
docs-partials/builder/docker/AwsAccessConfig-not-required.mdx
docs/README.md
docs/builders/docker.mdx
docs/post-processors/docker-push.mdx
post-processor/docker-push/post-processor.hcl2spec.go
post-processor/docker-push/post-processor_test.go

fix: made ECR type checker flexible to accept the server w/o https

---

docs/builders/docker.mdx

Fixes the syntax of the `Tabs` component usage in the builder docs.

fix: Tabs syntax in docs

---

builder/docker/ecr_login.go
post-processor/docker-push/post-processor_test.go
post-processor/docker-tag/post-processor_test.go

Running `golangci-lint` on the repository returns some errors, so we fix them in this PR.

Fix lint errors

---

builder/docker/config.go
docs-partials/builder/docker/Config-not-required.mdx
docs-partials/builder/docker/Config-required.mdx
docs/builders/docker.mdx
docs/post-processors/docker-import.mdx
docs/post-processors/docker-push.mdx
docs/post-processors/docker-save.mdx
docs/post-processors/docker-tag.mdx

With the move to developer.hashicorp.com some links between the general doc and plugins were broken. This PR fixes them

docs: fix references to internal documentation

---

builder/docker/driver_docker.go

```hcl
source "docker" "docker" {
image          = "amazonlinux"
export_path    = "image.tar"
privileged     = true
aws_profile    = var.aws_profile
volumes = {
"~/.aws" = "/root/.aws"
}
}
```
Closes #63

Support "~/" in host volume path

---

docs/builders/docker.mdx

For the Windows image example in HCL2, we described the image as `ubuntu' where it should have been a Windows image, so this commit fixes that problem by using the same image base as the JSON example.
Closes #153

docs: fix windows image in example

---

docs/builders/docker.mdx
docs/post-processors/docker-push.mdx

Adds some missing links to the AWS credential guide. 
Ran `make generate` after committing changes, which did not result in a diff, so I believe this should be sufficient.

docs: Add missing links to AWS credential guide

---

docs/builders/docker.mdx
docs/post-processors/docker-import.mdx
docs/post-processors/docker-save.mdx
docs/post-processors/docker-tag.mdx

Swaps order of HCL2/JSON example code tabs so that the HCL2 tab is the default
Ran `make generate` after committing changes, which did not result in a diff, so I believe this should be sufficient.
Note: The diff looks weird because git diff is getting confused by the similar blocks of code. For easier reading, I split the changes into two commits where the swaps aren't being confused by git diff.

docs: Swap order of HCL2/JSON example code tabs so that the HCL2 tab is the default

---

builder/docker/builder.go
builder/docker/driver_docker.go
builder/docker/step_set_defaults.go

With this change the images built will by default get the CMD and ENTRYPOINT from the source image if not overwritten by a user in the `changes` configuration option.
This replicates the behavior when building images from a Dockerfile.
I found numerous complaints which all seem to be related to the behaviour of the docker builder overwriting the CMD / ENTRYPOINT which this change should solve. (Kind of surprising to see that this hasn't been fixed yet 😵‍)
Closes #158
Closes #132
Closes #13 
Closes #9
Closes https://github.com/hashicorp/packer/issues/4914

feat: use CMD/ENTRYPOINT from source image by default

---

builder/docker/driver_docker.go
builder/docker/step_set_defaults.go

The code to set the default values for cmd/entrypoint in order to inherit what was set from the original image was working well if both the cmd and entrypoint were set, but if the entrypoint was null, the resulting image would inherit the temporary container's, which was /bin/sh.
This resulted in some images being built incorrectly, with `/bin/sh` as entrypoint, regardless of what we had as CMD/ENTRYPOINT in this case.
To fix this issue, we return a JSON array with an empty string if the entrypoint or the CMD was null in the image, and we haven't decided to override it.
This effectively forces the resulting image to have an equivalent of null as the CMD/ENTRYPOINT, which makes the final image honour the behaviour from the source image.
Closes #176 
cc: @gardar for insights, as you had …

builder: force an empty cmd/entrypoint if unset

---

.web-docs/components/builder/docker/README.md
builder/docker/builder.go
builder/docker/communicator.go
builder/docker/config.go
builder/docker/config.hcl2spec.go
builder/docker/driver_docker.go
builder/docker/step_connect_docker.go
docs-partials/builder/docker/Config-not-required.mdx
post-processor/docker-import/post-processor.go
post-processor/docker-import/post-processor.hcl2spec.go
post-processor/docker-push/post-processor.go
post-processor/docker-push/post-processor.hcl2spec.go
post-processor/docker-save/post-processor.go
post-processor/docker-save/post-processor.hcl2spec.go
post-processor/docker-tag/post-processor.go
post-processor/docker-tag/post-processor.hcl2spec.go

When using the builder to create a new container image, we used to default on using the `docker` command for everything.
While this is simple, this can limit what users try to do with the plugin, typically if they need to run their builds on a specific version of Docker which they built from scratch and won't install it, or if they want to build with a Docker-compatible alternative like `podman`.
To circumvent this limitation, we add a new `docker_path` option to the builder, so they can use this to use alternative docker binaries for orchestrating their builds with.

Alt executable support

---

.web-docs/components/builder/docker/README.md
builder/docker/dockerfile_config.go
builder/docker/dockerfile_config.hcl2spec.go
builder/docker/driver_docker.go
docs-partials/builder/docker/DockerfileBootstrapConfig-not-required.mdx

This PR adds support under the `build` section to specify the `arguments` value when bootstrapping a packer build using a Dockerfile.  More specifically, when specifying an optional `build.arguments` value, which must be a map of key / value pairs corresponding to the name / value of docker ARGs, the plugin will add `--build-arg <key>=<value>` to the arguments passed to `docker build` for each record in the map, allowing the user to specify or override build-time arguments .

Adds initial support for build.arguments

---

.web-docs/components/builder/docker/README.md
docs/builders/docker.mdx

Minor fix to code block '```' guards.
It looks like the `**JSON**` bits were put in by a git merge or something because they were right in the middle of the `hcl` example.

Fix: Update docker.mdx

---

.web-docs/components/builder/docker/README.md
builder/docker/config.go
builder/docker/step_build.go
docs-partials/builder/docker/Config-not-required.mdx

This PR adds support for performing `docker login` before commencing the build step when bootstrapping a packer build using a Dockerfile. More specifically, these changes add analogous logic to the build step from the pull step to attempt to authenticate with the information specified in the `login_server`, `login_username`, and `login_password` config options when the `login` value is true, or via ECR when the `ecr_login` value is true.  This allows the user to build images from a private docker repository when performing a bootstrapped build from a Dockerfile.
Closes #194

Adds initial support for login before bootstrapped build step

---

builder/docker/config_test.go
builder/docker/dockerfile_config.go
builder/docker/dockerfile_config_test.go
go.mod

The IsDefault function on DockerfileBootstrapConfig was implemented manually with the few arguments supported initially, but wasn't updated when subsequent attributes were added.
This commit fixes that by changing how IsDefault is implemented by leveraging go-cmp for comparing the data, ignoring the arguments map, so we can compare that with both the empty map and a nil map, so they are considered default in both cases.
Simple equality wouldn't work on the structure because maps within a structure cannot be compared, so using `==` would provoke a compile-time error, which is handled with this approach, while supporting other new arguments out of the box for later changes.

builder: fix IsDefault with new arguments
